CREATE TABLE ROLES (
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(15) NOT NULL
);

CREATE TABLE USER_TO_ROLE (
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    FK_USER_ID LONG NOT NULL,
    FK_ROLE_ID LONG NOT NULL,
    CONSTRAINT FK_UTR_TO_USERS FOREIGN KEY(FK_USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_UTR_TO_ROLES FOREIGN KEY(FK_ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE USER (
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    TOKEN VARCHAR(80) NOT NULL,
);

CREATE TABLE CATEGORIES (
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCTS (
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    PRICE DOUBLE NOT NULL,
    FK_CATEGORY_ID LONG,
    CONSTRAINT PRODUCTS FOREIGN KEY(FK_CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

